import React, {useState, useEffect} from 'react';
import {Text, ScrollView, StyleSheet} from 'react-native'
import GText from '../../../components/GText'
import {fsize, fWeight, color, fAlign, ffamily, radius} from '../../../theme';

export default () => {
    return (
        <ScrollView contentContainerStyle={style.scrollView}>
            
                <GText
                fontSize={fsize.h6}
                color={color.navyBlue}
                style={{marginTop: 20, marginBottom:10, marginHorizontal:20}}>
                    <Text style={{fontWeight: "bold"}}>GoMotorCar Pvt Ltd</Text> hereinafter referred to as <Text style={{fontWeight: "bold"}}>GoMotorCar</Text> and <Text style={{fontWeight: "bold"}}>GoMotorCar website and mobile application</Text> collectively referred as <Text style={{fontWeight: "bold"}}>GoMotorCar online platform.</Text>
                </GText>
            
                <GText
                fontSize={fsize.h6}
                color={color.navyBlue}
                style={{marginTop: 10, marginBottom:10, marginHorizontal:20}}>
                    We uniquely respect your privacy and value your trust vested in us. Purpose of this Privacy Policy is to make you aware about the methods and practices through which GoMotorCar collects stores and uses the information shared on GoMotorCar online platform.
                </GText>
            

                <GText
                fontSize={fsize.h6}
                color={color.navyBlue}
                style={{marginTop: 10, marginBottom:10, marginHorizontal:20}}>
                    For better understanding and the transparency, it is advised that you read the policy with utmost care. After going through below details, you unconditionally give us consent to use & disclose your personal information in accordance with this Privacy Policy.
                </GText>
                <GText
                fontSize={fsize.h6}
                color={color.navyBlue}
                style={{marginTop: 10, marginBottom:10, marginHorizontal:20}}>
                    <Text style={{fontWeight: "bold"}}>Consent:</Text> By Using GoMotorCar online platform, you hereby consent to our Privacy Policy and agree to its terms. In case if you do not agree to the policy terms, we advise you not to use the GoMotorCar online platform.
                </GText>
                <GText
                fontSize={fsize.h6}
                color={color.navyBlue}
                style={{marginTop: 10, marginBottom:10, marginHorizontal:20}}>
                    <Text style={{fontWeight: "bold"}}>General:</Text> The information collected on GoMotorCar Website and Mobile Application is used to facilitate for the requested services by you. We do not provide any information to third party for commercial use or marketing purpose. Only certified service partners get access to limited information upon request for services from you.
                </GText>
                <GText
                fontSize={fsize.h6}
                color={color.navyBlue}
                style={{marginTop: 10, marginBottom:10, marginHorizontal:20}}>
                    <Text style={{fontWeight: "bold"}}>Personal Information and others:</Text> We collect email, Mobile No, Address, vehicle details and service location as provide by you in order to use the services. Time to time changes done by you are also stored. We do not store any payment related information like Account details card holder name, credit card number, CVV and debit card number or expiration date. Payment services used by us are provided by third party and we have taken sufficient measures to ensure that third parties are statutory complaint.
                </GText>
                <GText
                fontSize={fsize.h6}
                color={color.navyBlue}
                style={{marginTop: 10, marginBottom:10, marginHorizontal:20}}>
                    <Text style={{fontWeight: "bold"}}>Information Usage:</Text> Collected information is used to cater to the requested services in desired manner. It may lead to communicate with you, either directly or through one of our certified partner, including GoMotorCar customer service, to provide you with you updates and other information relating to the services and GoMotorCar online platform
                </GText>
                <GText
                fontSize={fsize.h6}
                color={color.navyBlue}
                style={{marginTop: 10, marginBottom:10, marginHorizontal:20}}>
                    <Text style={{fontWeight: "bold"}}>Cookies:</Text> By Definition and standards, a cookie is a small amount of data generated by a website and saved by your web browser. Its purpose is to remember information about you. GoMotorCar uses cookie. We do not collect any personal information via cookies
                </GText>
                <GText
                fontSize={fsize.h6}
                color={color.navyBlue}
                style={{marginTop: 10, marginBottom:10, marginHorizontal:20}}>
                    <Text style={{fontWeight: "bold"}}>Security:</Text> Our endeavour is to best protect the information shared, stored and used. We take reasonable technical and organisational precautions to prevent the loss, misuse or alteration of your personal information. We store all the personal information you provide on our secure servers. Only authorised people have access to, custody of and the means of using personal data, we collect.
                </GText>
                <GText
                fontSize={fsize.h6}
                color={color.navyBlue}
                style={{marginTop: 10, marginBottom:20, marginHorizontal:20}}>
                    Request you to kindly review the policy periodically since it can be subject to changes time to time in accordance with statutory regulations. For any grievance you can request a call back from website of Mobile application through request a call back section.
                </GText>
        
        </ScrollView>
    );
}

const style = StyleSheet.create({
    viewStyle: {
        flex: 1,
        justifyContent: 'space-around',
        flexDirection: 'row',
        fontSize: fsize.p2,
        color: color.blue,
        alignItems: 'center'
    },
    scrollView: {
        flexGrow: 1,
        backgroundColor: color.white,
    }
});